### ISSUE TITLE
Distinguish empty map types 

### ISSUE THREAD

**Issue by yxu1111** [jmattheis/goverter#126] opened 2024-01-25 06:35 UTC
**Describe the bug**
A nil map is always converted to an empty map ({}) which sometimes could cause issues if the caller treats them differently

**To Reproduce**
pass in a member variable that is a map of value nil will return a map of value '{}'

**Expected behavior**
Ideally it should keep the original behavior - nil to nil and {} to {}

Thanks!

**Comment by jmattheis** [comment] 2024-01-25 17:02
Thanks for the report, could you try out the `map-nil` branch and verify the problem is fixed for you?

- `go install github.com/jmattheis/goverter/cmd/goverter@map-nil`
- or `go run github.com/jmattheis/goverter/cmd/goverter@map-nil [pattern]`
- or `go get github.com/jmattheis/goverter@map-nil`

**Comment by yxu1111** [comment] 2024-01-26 03:50
yes, it works great! Thank you for your in-time response and quick fix!

**Comment by jmattheis** [comment] 2024-01-27 16:45
Released with [`v1.3.1`](https://goverter.jmattheis.de/changelog#v1-3-1).

**Closed by jmattheis** 2024-01-27 16:45 UTC
Labels: bug
